### ISSUE TITLE
After upgrading to 2.0.9 homebridge crashes on load of module

### ISSUE THREAD

**Issue by birnbam** [grzegorz914/homebridge-openwebif-tv#10]
Hi,
The newest version 2.0.9 crashes my homebridge on module load, even when not specified in config:

Load homebridge-openwebif-tv.OpenWebIfTv
[1/20/2020, 5:09:34 PM] TypeError: Cannot read property 'checkSatateInterval' of null
    at new openwebifPlatform (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:28:34)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[1/20/2020, 5:09:34 PM] Got SIGTERM, shutting down Homebridge...

**Comment by grzegorz914** [comment]
Please post Your config

**Comment by grzegorz914** [comment]
Fixed in 2.0.10

**Comment by birnbam** [comment]
Issue still exists in 2.0..10

I run multiple homebridge instances on the same Ubuntu computer.
So this is the reason why I have openwebiftv installed but not configured in this config file.

My config:
`{
  "bridge": {
    "name": "Homebridge-test",
    "username": "D4:BE:D9:11:D3:FF",
    "port": 51825,
    "pin": "045-44-000"
   },
  "description": "Robert's HomeBridge-test",
  "accessories": [
     {
        "accessory": "mqttthing",
        "type": "lightbulb",
        "name": "Test SonOFF",
        "caption": "Test Sonoff",
        "url": "mqtt://localhost.",
        "username": "user",
        "password": "pass",
        "topics": {
                        "getOnline": "tele/Kommode-EZ/LWT",
                        "getOn":     "stat/Kommode-EZ/POWER",
                        "setOn":     "cmnd/Kommode-EZ/POWER"
                  },
        "onValue": "ON",
        "offValue": "OFF",
        "onlineValue": "Online",
        "manufacturer": "ITEAD",
        "model": "SonOff RF",
        "serialNumber": "0815"
     }
  ],
  "platforms": [
    {
      "platform" : "eWeLink",
      "name" : "eWeLink",
      "countryCode" : "43",
      "password" : "your-login-password",
      "imei" : "00034567-89AB-CDEF-0123-456789ABCDEF"
    }
  ]
} `

The error message:
`homebridge -D -U /home/robert/.homebridge-test
[1/21/2020, 8:55:53 PM] Loaded config.json with 1 accessories and 1 platforms.
[1/21/2020, 8:55:53 PM] ---
[1/21/2020, 8:55:53 PM] Loaded plugin: homebridge-automation-switches
[1/21/2020, 8:55:53 PM] Registering platform 'homebridge-switches.AutomationSwitches'
[1/21/2020, 8:55:53 PM] ---
[1/21/2020, 8:55:53 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/21/2020, 8:55:53 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/21/2020, 8:55:53 PM] ---
[1/21/2020, 8:55:53 PM] Loaded plugin: homebridge-cmdswitch2
[1/21/2020, 8:55:53 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[1/21/2020, 8:55:53 PM] ---
[1/21/2020, 8:55:53 PM] Loaded plugin: homebridge-cmdtrigger
[1/21/2020, 8:55:53 PM] Registering accessory 'homebridge-cmdtrigger.CmdTrigger'
[1/21/2020, 8:55:53 PM] ---
[1/21/2020, 8:55:53 PM] Loaded plugin: homebridge-ewelink-max
homebridge API version: 2.4
[1/21/2020, 8:55:53 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/21/2020, 8:55:53 PM] ---
[1/21/2020, 8:55:53 PM] Loaded plugin: homebridge-http-switch
[1/21/2020, 8:55:53 PM] Registering accessory 'homebridge-http-switch.HTTP-SWITCH'
[1/21/2020, 8:55:53 PM] ---
[1/21/2020, 8:55:53 PM] Loaded plugin: homebridge-ip-camera
[1/21/2020, 8:55:53 PM] Registering platform 'homebridge-ip-camera.Camera-IP'
[1/21/2020, 8:55:53 PM] ---
[1/21/2020, 8:55:53 PM] Loaded plugin: homebridge-mqtt-switch-tasmota
[1/21/2020, 8:55:53 PM] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[1/21/2020, 8:55:53 PM] ---
[1/21/2020, 8:55:54 PM] Loaded plugin: homebridge-mqttthing
[1/21/2020, 8:55:54 PM] Registering accessory 'homebridge-mqttthing.mqttthing'
[1/21/2020, 8:55:54 PM] ---
[1/21/2020, 8:55:54 PM] Loaded plugin: homebridge-netatmo
[1/21/2020, 8:55:54 PM] Registering platform 'homebridge-netatmo.netatmo'
[1/21/2020, 8:55:54 PM] ---
[1/21/2020, 8:55:54 PM] Loaded plugin: homebridge-openwebif-tv
[1/21/2020, 8:55:54 PM] Registering platform 'homebridge-openwebif-tv.OpenWebIfTv'
[1/21/2020, 8:55:54 PM] ---
[1/21/2020, 8:55:54 PM] Loaded plugin: homebridge-platform-wemo
[1/21/2020, 8:55:54 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[1/21/2020, 8:55:54 PM] ---
[1/21/2020, 8:55:54 PM] Loaded plugin: homebridge-tplink-smarthome
[1/21/2020, 8:55:54 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[1/21/2020, 8:55:54 PM] ---
[1/21/2020, 8:55:54 PM] Loading 1 platforms...
[1/21/2020, 8:55:54 PM] [eWeLink] Initializing eWeLink platform...
[1/21/2020, 8:55:54 PM] [eWeLink] Initialization skipped. Missing configuration data.
[1/21/2020, 8:55:54 PM] Loading 1 accessories...
[1/21/2020, 8:55:54 PM] [Test SonOFF] Initializing mqttthing accessory...
Load homebridge-switches.AutomationSwitches
[1/21/2020, 8:55:54 PM] [homebridge-switches.AutomationSwitches] AutomationSwitchesPlatform Plugin Loaded - Version 3.2.1
Load homebridge-camera-ffmpeg.Camera-ffmpeg
Load homebridge-cmdswitch2.cmdSwitch2
Load homebridge-ip-camera.Camera-IP
Load homebridge-openwebif-tv.OpenWebIfTv
[1/21/2020, 8:55:54 PM] TypeError: Cannot read property 'checkStateInterwal' of null
    at new openwebifPlatform (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:28:34)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[1/21/2020, 8:55:54 PM] Got SIGTERM, shutting down Homebridge... `

**Comment by grzegorz914** [comment]
OK, I think in 2.0.11 finally fixed

**Comment by birnbam** [comment]
Unfortunately not fixed...
upgraded to 2.0.11 and this is the log:

Load homebridge-openwebif-tv.OpenWebIfTv
**[1/22/2020, 4:45:23 PM] TypeError: Cannot read property 'checkStateInterval' of null**
    at new openwebifPlatform (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:28:34)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
**[1/22/2020, 4:45:23 PM] Got SIGTERM, shutting down Homebridge...**

**Comment by grzegorz914** [comment]
Sorry but Your config doesn’t contain Settings for OpenWebIfTv

**Comment by birnbam** [comment]
Did you test on ubuntu? mybe they do not occur on other platforms -  I still run in problems:

1.  when no settings for openwebiftv  in config.json --> homebridge crashes.
2. when settings for openwebiftv in config.json --> homebridge crashes.

**Here is a config.json with openwebiftv settings in it:**
{
  "bridge": {
    "name": "Homebridge-01",
    "username": "D4:BE:D9:11:D3:F8",
    "port": 51827,
    "pin": "037-51-378"
   },
  "description": "Robert's HomeBridge-01",
  "accessories": [
     {
     }
  ],
  "platforms": [
     {
        "platform": "OpenWebIfTv",
        "checkStateInterval": 5,
        "devices": [{
                "name": "VU",
                "host": "10.10.0.223",
                "port": "80",
                "auth": false,
                "user": "root",
                "pass": "",
                "switchInfoMenu": true,
        "bouquets": [
          {
            "name": "gotv neu",
            "reference": "1:0:16:3404:3ED:1:C00000:0:0:0:"
          },
          {
            "name": "ORF1 HD",
            "reference": "1:0:19:132F:3EF:1:C00000:0:0:0:"
          },
          {
            "name": "Radio Antenne Bayern",
            "reference": "1:0:2:AA:7:85:C00000:0:0:0:"
          }
          ]
        }
      ]
    }
  ]
}


**Here is the output**
sudo homebridge -D -U ~/.homebridge-01
[sudo] password for robert: 
[1/22/2020, 6:33:11 PM] Loaded config.json with 1 accessories and 1 platforms.
[1/22/2020, 6:33:11 PM] ---
[1/22/2020, 6:33:11 PM] Loaded plugin: homebridge-automation-switches
[1/22/2020, 6:33:11 PM] Registering platform 'homebridge-switches.AutomationSwitches'
[1/22/2020, 6:33:11 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-camera-ffmpeg
[1/22/2020, 6:33:12 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-cmdswitch2
[1/22/2020, 6:33:12 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-cmdtrigger
[1/22/2020, 6:33:12 PM] Registering accessory 'homebridge-cmdtrigger.CmdTrigger'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-ewelink-max
homebridge API version: 2.4
[1/22/2020, 6:33:12 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-http-switch
[1/22/2020, 6:33:12 PM] Registering accessory 'homebridge-http-switch.HTTP-SWITCH'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-ip-camera
[1/22/2020, 6:33:12 PM] Registering platform 'homebridge-ip-camera.Camera-IP'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-mqtt-switch-tasmota
[1/22/2020, 6:33:12 PM] Registering accessory 'homebridge-mqtt-switch-tasmota.mqtt-switch-tasmota'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-mqttthing
[1/22/2020, 6:33:12 PM] Registering accessory 'homebridge-mqttthing.mqttthing'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-netatmo
[1/22/2020, 6:33:12 PM] Registering platform 'homebridge-netatmo.netatmo'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-openwebif-tv
[1/22/2020, 6:33:12 PM] Registering platform 'homebridge-openwebif-tv.OpenWebIfTv'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:12 PM] Loaded plugin: homebridge-openwebif-tv
[1/22/2020, 6:33:12 PM] Registering platform 'homebridge-openwebif-tv.OpenWebIfTv'
[1/22/2020, 6:33:12 PM] ---
[1/22/2020, 6:33:13 PM] Loaded plugin: homebridge-platform-wemo
[1/22/2020, 6:33:13 PM] Registering platform 'homebridge-platform-wemo.BelkinWeMo'
[1/22/2020, 6:33:13 PM] ---
[1/22/2020, 6:33:13 PM] Loaded plugin: homebridge-tplink-smarthome
[1/22/2020, 6:33:13 PM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[1/22/2020, 6:33:13 PM] ---
[1/22/2020, 6:33:13 PM] Loading 1 platforms...
[1/22/2020, 6:33:13 PM] [OpenWebIfTv] Initializing OpenWebIfTv platform...
[1/22/2020, 6:33:13 PM] [OpenWebIfTv] Error while getting information of device: 10.10.0.223, error: Error: Invalid protocol: undefined10.10.0.223:
    at Request.init (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:458:31)
    at new Request (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:127:8)
    at request (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/index.js:53:10)
    at tvClient.getDeviceInfo (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:122:3)
    at new tvClient (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:75:8)
    at new openwebifPlatform (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:38:28)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:337:32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[1/22/2020, 6:33:13 PM] [OpenWebIfTv] Channels file for device: 10.10.0.223, will be created and saved in /home/robert/.openwebifTv/
[1/22/2020, 6:33:13 PM] Loading 1 accessories...
[1/22/2020, 6:33:13 PM] TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[1/22/2020, 6:33:13 PM] Got SIGTERM, shutting down Homebridge...
[1/22/2020, 6:33:13 PM] [OpenWebIfTv] Can not acces device: 10.10.0.223. Might be due to a wrong settings in config, error ReferenceError: string is not defined
    at tvClient.printBouquetsDetail (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:625:10)
    at /usr/lib/node_modules/homebridge-openwebif-tv/index.js:615:8
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:359:8)
    at JSON.stringify (<anonymous>)
    at tvClient.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:354:24)
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:377:5)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21):
[1/22/2020, 6:33:13 PM] [OpenWebIfTv] error: ReferenceError: string is not defined
[1/22/2020, 6:33:14 PM] [OpenWebIfTv] setupTvService
[1/22/2020, 6:33:14 PM] [OpenWebIfTv] setupTvSpeakerService
[1/22/2020, 6:33:14 PM] [OpenWebIfTv] prepareInputServices
[1/22/2020, 6:33:14 PM] [OpenWebIfTv] publishExternalAccessories for device: 10.10.0.223
[1/22/2020, 6:33:14 PM] VU is running on port 34879.
[1/22/2020, 6:33:14 PM] Please add [VU] manually in Home app. Setup Code: 037-51-378
robert@birnbam105:~/.homebridge-01$

**Comment by grzegorz914** [comment]
Check please 2.0.12

**Comment by birnbam** [comment]
Upgraded to 2.0.12 - still not working. Can you please double-check my posted config, since I get still following error:
```
[1/22/2020, 8:39:07 PM] Loading 1 platforms...
[1/22/2020, 8:39:07 PM] [OpenWebIfTv] Initializing OpenWebIfTv platform...
[1/22/2020, 8:39:07 PM] [OpenWebIfTv] Error while getting information of device: 10.10.0.223, error: Error: Invalid protocol: undefined10.10.0.223:
    at Request.init (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:458:31)
    at new Request (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:127:8)
```

and later on:
```
[1/22/2020, 8:39:07 PM] [OpenWebIfTv] Channels file for device: 10.10.0.223, will be created and saved in /home/robert/.openwebifTv/
[1/22/2020, 8:39:07 PM] Loading 1 accessories...
[1/22/2020, 8:39:07 PM] TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[1/22/2020, 8:39:07 PM] Got SIGTERM, shutting down Homebridge...
```

**Comment by grzegorz914** [comment]
Check 2.0.14

**Comment by birnbam** [comment]
... still no luck with 2.0.13 ...  Am I missing some config entries?

```
[1/22/2020, 10:06:27 PM] Loading 2 platforms...
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] Initializing OpenWebIfTv platform...
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] Channels file for device: 10.10.0.223, will be created and saved in /home/robert/.openwebifTv/
[1/22/2020, 10:06:27 PM] [eWeLink] Initializing eWeLink platform...
[1/22/2020, 10:06:27 PM] [eWeLink] Initialization skipped. Missing configuration data.
[1/22/2020, 10:06:27 PM] Loading 1 accessories...
[1/22/2020, 10:06:27 PM] TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:50:12)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
[1/22/2020, 10:06:27 PM] Got SIGTERM, shutting down Homebridge...
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] -----Device 10.10.0.223-----
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] Manufacturer: Vu+
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] Model: undefined
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] Kernel: 3.14.28
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] Chipset: 7444s
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] Firmware: 2019-10-05-vti-master (5ede501b9)
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] Webif version.: OWIF 1.2.8
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] Can not acces device: 10.10.0.223. Might be due to a wrong settings in config, error TypeError: Cannot read property 'host' of undefined
    at tvClient.printBouquetsDetail (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:625:64)
    at /usr/lib/node_modules/homebridge-openwebif-tv/index.js:614:8
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:358:8)
    at JSON.stringify (<anonymous>)
    at tvClient.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:353:24)
    at Request._callback (/usr/lib/node_modules/homebridge-openwebif-tv/index.js:376:5)
    at Request.self.callback (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-openwebif-tv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21):
[1/22/2020, 10:06:27 PM] [OpenWebIfTv] error: TypeError: Cannot read property 'host' of undefined
[1/22/2020, 10:06:28 PM] [OpenWebIfTv] setupTvService
[1/22/2020, 10:06:28 PM] [OpenWebIfTv] setupTvSpeakerService
[1/22/2020, 10:06:28 PM] [OpenWebIfTv] prepareInputServices
[1/22/2020, 10:06:28 PM] [OpenWebIfTv] publishExternalAccessories for device: 10.10.0.223
[1/22/2020, 10:06:28 PM] Fernseher is running on port 33481.
[1/22/2020, 10:06:28 PM] Please add [Fernseher] manually in Home app. Setup Code: 037-51-378
```

**Comment by grzegorz914** [comment]
Looks like finally is working, this Error getting only after homebridge reboot, i will check this but im on Holiday and no mich time now.

**Comment by birnbam** [comment]
Did you read this line in the log?
``
[1/22/2020, 10:06:27 PM] Got SIGTERM, shutting down Homebridge...
[``

This tells that homebridge crashed before I can use the device...

So waiting for your update after your holidays, enjoy your time
