### ISSUE TITLE
Turning off Vu+ Uno 4K

### ISSUE THREAD

**Issue by fnolting** [grzegorz914/homebridge-openwebif-tv#16]
I used to control my sat receiver with this pugin but turning it off won't function anymore. I'm exposing it to HomeKit and when I touch it it responds with "no answer". In the homebridge logs I see this:

[OpenWebIfTv] Device: vuuno4k.local, get current Channel successfull: (...)
[OpenWebIfTv] Device: vuuno4k.local, get current Power state successfull: ON
[OpenWebIfTv] Device: vuuno4k.local, set new Power state successfull: ON

And during a restart of the homebridge service I see this:
[ConfigUI] [HapClient] [192.168.x.x:34499 (1E:AT:DE:AD:BE:EF)] Failed to set value for VU+ Uno 4K.
[ConfigUI] Error: socket hang up

It seems that it sets the power state to ON even if it's already on. That already worked but stopped working with one of the recent releases.

**Comment by grzegorz914** [comment]
Fixed in 2.2.0, please make update.

**Comment by fnolting** [comment]
Unfortunately, that didn't fix the issue for me. Before the update, I could switch channels and turn it on. Now I can't control anything and it keeps telling me "no answer" in homekit. Nothing in homebridge logs either. Already restarted homebridge service.

**Comment by grzegorz914** [comment]
Please remove the Device from HomeKit app and add it again.

**Comment by fnolting** [comment]
That worked! :) Keep up the good work, really appreciate it!
